//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDue2.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToDue2.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The \&quot;Auto reorder option\&quot; is enabled which stops you from this operation\n Do you want to turn off this setting?\n This notification will not show up again. 的本地化字符串。
        /// </summary>
        public static string ConfirmationMessageText {
            get {
                return ResourceManager.GetString("ConfirmationMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Infor 的本地化字符串。
        /// </summary>
        public static string ConfirmationMessageTitle {
            get {
                return ResourceManager.GetString("ConfirmationMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Something to do ... 的本地化字符串。
        /// </summary>
        public static string MainPageTipText {
            get {
                return ResourceManager.GetString("MainPageTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically reorder todo 的本地化字符串。
        /// </summary>
        public static string MenuItemAdvancedAutoReorder {
            get {
                return ResourceManager.GetString("MenuItemAdvancedAutoReorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string MenuItemAdvancedRefresh {
            get {
                return ResourceManager.GetString("MenuItemAdvancedRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset position 的本地化字符串。
        /// </summary>
        public static string MenuItemAdvancedReset {
            get {
                return ResourceManager.GetString("MenuItemAdvancedReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark (Reload required) 的本地化字符串。
        /// </summary>
        public static string MenuItemDark {
            get {
                return ResourceManager.GetString("MenuItemDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string MenuItemExit {
            get {
                return ResourceManager.GetString("MenuItemExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 High Contrast 的本地化字符串。
        /// </summary>
        public static string MenuItemHighContrast {
            get {
                return ResourceManager.GetString("MenuItemHighContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monochrome 的本地化字符串。
        /// </summary>
        public static string MenuItemMonochrome {
            get {
                return ResourceManager.GetString("MenuItemMonochrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal 的本地化字符串。
        /// </summary>
        public static string MenuItemScaleLarge {
            get {
                return ResourceManager.GetString("MenuItemScaleLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Large 的本地化字符串。
        /// </summary>
        public static string MenuItemScaleNormal {
            get {
                return ResourceManager.GetString("MenuItemScaleNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Small 的本地化字符串。
        /// </summary>
        public static string MenuItemScaleSmall {
            get {
                return ResourceManager.GetString("MenuItemScaleSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show background 的本地化字符串。
        /// </summary>
        public static string MenuItemShowBackground {
            get {
                return ResourceManager.GetString("MenuItemShowBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced 的本地化字符串。
        /// </summary>
        public static string MenuItemTitleAdvanced {
            get {
                return ResourceManager.GetString("MenuItemTitleAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opacity 的本地化字符串。
        /// </summary>
        public static string MenuItemTitleOpacity {
            get {
                return ResourceManager.GetString("MenuItemTitleOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Palette (reload required) 的本地化字符串。
        /// </summary>
        public static string MenuItemTitlePalette {
            get {
                return ResourceManager.GetString("MenuItemTitlePalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scale 的本地化字符串。
        /// </summary>
        public static string MenuItemTitleScale {
            get {
                return ResourceManager.GetString("MenuItemTitleScale", resourceCulture);
            }
        }
    }
}
